alias ss='script/server'
alias sc='script/console --irb=pry'
alias sg='script/generate'
alias sd='script/destroy'

alias be='bundle exec'
alias bec='be cucumber'
alias po='be rake smartling:push smartling:pull'
alias deploy='be cap $(git_branch) deploy'
alias migrate='be rake db:migrate db:test:prepare'
alias cc='be compass compile'
alias unicorn='bundle exec unicorn_rails -c ./config/unicorn/development.rb'
