export PATH="$HOME/.rbenv/bin:./bin:$HOME/.rbenv/shims:/usr/local/sbin:$HOME/.sfs:$ZSH/bin:$PATH"
export MANPATH="/usr/local/man:/usr/local/mysql/man:/usr/local/git/man:$MANPATH"
export PATH="/usr/local/heroku/bin:$PATH"
export PATH="/usr/local/share/npm/bin:${PATH}"
export PATH="/usr/local/bin:$PATH"
