export PATH="./bin:$PATH"
export PATH="$ZSH/bin:$PATH"
export PATH="/usr/local/sbin:$PATH"
export PATH="/usr/local/heroku/bin:$PATH"
export PATH="/usr/local/share/npm/bin:${PATH}"
export PATH="/usr/local/bin:$PATH"
export PATH="/Applications/Postgres.app/Contents/Versions/9.6/bin/:$PATH"
export PATH="/Applications/SnowSQL.app/Contents/MacOS/:$PATH"

export MANPATH="/usr/local/man:/usr/local/mysql/man:/usr/local/git/man:$MANPATH"
